### ISSUE TITLE
`String movieId` is user in this method 

### ISSUE THREAD

**Issue by sonu3706** [stackroute/ibm-w1-tldm-server#10]
`    // this method is used update a existing user
    @Override
    public User updateUser(String movieId, User user) throws UserNotFoundException {
        User fetch = userRepo.findById(user.getUserId()).get();
        if (fetch != null) {
            userRepo.save(user);

        } else {
            throw new UserNotFoundException("user not found");
        }

        return user;
    }`

`String movieId` variable created in this method and that too it is not being used anywhere

**Comment by kartikeymishr** [comment]
fixed issue
