### ISSUE TITLE
Naming Conventions not followed

### ISSUE THREAD

**Issue by sonu3706** [stackroute/ibm-w1-tldm-server#11]
`
@Id
    private String id;
    private String messageContent;
    private Sender sender;
    private Receiver receiver;
    private Date createdAt;
`
Follow the naming conventions it should be 
`

    @Id
    private String messageId;
    private String messageContent;
    private Sender messageSender;
    private Receiver messageReciver;
    private Date messageCreatedAt;
`

**Comment by mggmanik** [comment]
fixed
