### ISSUE TITLE
Both Sender and Receiver should model is same

### ISSUE THREAD

**Issue by sonu3706** [stackroute/ibm-w1-tldm-server#12]
`public class Sender {

    private String userId;
    private String userName;
    private String name;
    private String userMail;
    private String phoneNum;

    public Sender() {
        super();
    }`

`public class Receiver {

    private String userId;
    private String userName;
    private String name;
    private String userMail;
    private String phoneNum;

    public Receiver() {
        super();
    }`

Both Sender and Receiver act as a User why there is need of two separate class. It can be accomadated in one User class refering to different responsebilities

**Comment by mggmanik** [comment]
fixed
