### ISSUE TITLE
Whole message object should be sent to the client

### ISSUE THREAD

**Issue by sonu3706** [stackroute/ibm-w1-tldm-server#13]
`    @MessageMapping("/chat")
    @SendTo("/topic/response")
    public MessageResponse messageResponse(Message message) throws Exception {
        messageService.saveMessage(message);
        String time = new SimpleDateFormat("h:mm a").format(message.getCreatedAt());
        return new MessageResponse(message.getMessageContent(), message.getSender(), message.getReceiver(), time);
    }`

There is no need of creating new MessageResponse class , same Message object should be sent to the client as we need whole message object

**Comment by mggmanik** [comment]
fixed
