### ISSUE TITLE
Both the method does the same work. Then why we have 2 request handler method??

### ISSUE THREAD

**Issue by sonu3706** [stackroute/ibm-w1-tldm-server#16]
`@GetMapping("/{channelName}")
    @ApiOperation("Get Detail of Channel by Channel Name")
    public ResponseEntity<?> getChannelByChannelName(@PathVariable String channelName) {
        ResponseEntity<?> responseEntity;
        Channel fetch;
        try {
            fetch = channelService.getChannelByChannelName(channelName);
            if (fetch != null) {
                responseEntity = new ResponseEntity<>(fetch, HttpStatus.OK);
            } else {
                responseEntity = new ResponseEntity<>("channel name not found", HttpStatus.NOT_FOUND);
            }
        } catch (ChannelNotFoundException e) {
            responseEntity = new ResponseEntity<>(e.getMessage(), HttpStatus.NOT_FOUND);

        }
        return responseEntity;
    }

    @GetMapping("/getchannel/{channelId}")
    public ResponseEntity<?> getChannelByChannelId(@PathVariable String channelId) {
        ResponseEntity<?> responseEntity;
        Channel fetch;
        try {
            fetch = channelService.getChannelByChannelId(channelId);
            if (fetch != null) {
                responseEntity = new ResponseEntity<>(fetch, HttpStatus.OK);
            } else {
                responseEntity = new ResponseEntity<>("channel id not found", HttpStatus.NOT_FOUND);
            }
        } catch (ChannelNotFoundException e) {
            responseEntity = new ResponseEntity<>(e.getMessage(), HttpStatus.NOT_FOUND);

        }
        return responseEntity;
    }
`

**Comment by Gaya397** [comment]
Removed duplicate handler methods in Channel Service.
