### ISSUE TITLE
Duplicate handler method

### ISSUE THREAD

**Issue by sonu3706** [stackroute/ibm-w1-tldm-server#17]
`  @GetMapping("/user/{userName}")
    @ApiOperation("Get the Channel by providing name of user")
    public ResponseEntity<?> getchannelByUserName(@PathVariable String userName) {
        ResponseEntity<?> responseEntity;
        List<Channel> fetchChannel = channelService.getListOfChannelsByUsers(userName);
        if (fetchChannel != null) {
            responseEntity = new ResponseEntity<>(fetchChannel, HttpStatus.OK);
        } else {
            responseEntity = new ResponseEntity<>("user name not found", HttpStatus.NOT_FOUND);
        }
        return responseEntity;
    }
`

` // this handler method is mapped to the URL "/users/{userId}" using HTTP GET method //
    @GetMapping("/users/{userId}")
    @ApiOperation("Get list of channel in which the user is present")
    public ResponseEntity<?> getchannelByUserId(@PathVariable String userId) {
        ResponseEntity<?> responseEntity;
        List<Channel> fetchChannel = channelService.getListOfChannelsByUser(userId);
        if (fetchChannel != null) {
            responseEntity = new ResponseEntity<>(fetchChannel, HttpStatus.OK);
        } else {
            responseEntity = new ResponseEntity<>("user name not found", HttpStatus.NOT_FOUND);
        }
        return responseEntity;
    }`

**Comment by Gaya397** [comment]
Duplicate handler methods removed in Channel Service.
