### ISSUE TITLE
Duplicate handler method created

### ISSUE THREAD

**Issue by sonu3706** [stackroute/ibm-w1-tldm-server#21]
`
    //update community:channels get added into the community using communityName
    @PutMapping("/update/{communityName}")
    public ResponseEntity<?> updateByCommunityName(@PathVariable String communityName, @RequestBody Channel channel, Community community) {
        ResponseEntity<?> responseEntity = null;
        try {
            communityService.updateByCommunityName(communityName, channel);

            responseEntity = new ResponseEntity<>(community, HttpStatus.OK);

        } catch (CommunityNotFoundException exception) {
            responseEntity = new ResponseEntity<>(exception.getMessage(), HttpStatus.NOT_FOUND);

        }

        return responseEntity;
    }

    //update community:channels get added into the community using communityId
    @PutMapping("/updated/{communityId")
    public ResponseEntity<?> updateByCommunityId(@PathVariable String communityId, @RequestBody Channel channel, Community community) {
        ResponseEntity<?> responseEntity = null;
        try {
            communityService.updateByCommunityId(communityId, channel);

            responseEntity = new ResponseEntity<>(communityId, HttpStatus.OK);

        } catch (CommunityNotFoundException exception) {
            responseEntity = new ResponseEntity<>(exception.getMessage(), HttpStatus.NOT_FOUND);

        }

        return responseEntity;
    }
`

**Comment by Rajashree-gano** [comment]
deleted update method (updateCommunityByCommunityName() )..
