### ISSUE TITLE
Duplicate request handler method

### ISSUE THREAD

**Issue by sonu3706** [stackroute/ibm-w1-tldm-server#8]
`    // this handler method is mapped to the URL "/api/user/name/{userName}" using  HTTP GET method
    @GetMapping("/name/{name}")
    public ResponseEntity<?> showMethod(@PathVariable String name) {
        ResponseEntity<?> responseEntity = null;

        try {
            if (service.getUserByName(name) != null) {
                responseEntity = new ResponseEntity<>(service.getUserByName(name), HttpStatus.OK);

            } else {
                responseEntity = new ResponseEntity<>("user not found", HttpStatus.NOT_FOUND);
            }
        } catch (UserNotFoundException e) {
            responseEntity = new ResponseEntity<>("user not found", HttpStatus.NOT_FOUND);
        }

        return responseEntity;
    }

  // this handler method is mapped to the URL "/api/user/{Id}" using  HTTP GET method
    @GetMapping("/{id}")
    public ResponseEntity<?> getUserById(@PathVariable String id) {
        ResponseEntity<?> responseEntity;
        User fetch;
        try {
            fetch = service.getUserById(id);
            if (fetch != null) {
                responseEntity = new ResponseEntity<>(fetch, HttpStatus.OK);
            } else {
                responseEntity = new ResponseEntity<>("user details for id is not found", HttpStatus.NOT_FOUND);
            }
        } catch (UserNotFoundException e) {
            responseEntity = new ResponseEntity<>(e.getMessage(), HttpStatus.NOT_FOUND);
        }

        return responseEntity;
    }

`
Any reason for the above two handler method

**Comment by kartikeymishr** [comment]
fixed issue
