### ISSUE TITLE
Duplicate code in Service layer of UserService

### ISSUE THREAD

**Issue by sonu3706** [stackroute/ibm-w1-tldm-server#9]
`
    // this method is used to get a user by userId
    @Override
    public User getUserById(String userId) throws UserNotFoundException {
        User fetchUser;
        try {
            fetchUser = userRepo.findById(userId).get();
        } catch (NoSuchElementException exception) {
            throw new UserNotFoundException("User not found");
        }

        return fetchUser;
    }

    // this method is used to get a user by userName
    @Override
    public User getUserByUserName(String userName) throws UserNotFoundException {
        User user;
        try {
            user = userRepo.getUserByUserName(userName);
        } catch (NoSuchElementException exception) {
            throw new UserNotFoundException("User not found");
        }

        return user;
    }

    @Override
    public User getUserByName(String name) throws UserNotFoundException {
        User user;
        try {
            user = userRepo.getUserByName(name);
        } catch (NoSuchElementException exception) {
            throw new UserNotFoundException("User not found");
        }
        return user;
    }

    // this method is used to get the list of users
    @Override
    public List<User> getAllUsers() {
        List<User> userList = userRepo.findAll();
        return userList;
    }`

**Comment by kartikeymishr** [comment]
fixed issue
